language: python
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
python:
  - "3.6"
install:
  - pushd /tmp
  - wget https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
  - unzip protoc-3.7.1-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
script:
  - chmod +x ./compile.py
  - ./compile.py python --generate_desc --include_imports --include_source_info
  # Test Scripts...
  - chmod +x ./dummyDump.py
  - ./dummyDump.py
  - chmod +x ./extractDump.py
  - ./extractDump.py
  # Todo Decode
  #- chmod +x ./decode.sh
  #- ./decode.sh ./GameDataWrapper.bytes
  # Compile Single need revision
  #- - chmod +x ./compile_single.py
  #- ./compile_single.py -d -o out2
  #- clang-format-3.8 -i -style file $(find src -name "*.proto")
  #- git diff --exit-code
